/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:0d8a5471-8397-40ee-941b-aa9395b49e15",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_598BxuqtW",
    "aws_user_pools_web_client_id": "5r1v1188p9dmpiskmqi8jq8si6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "sa-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "patient-db-dev",
            "region": "sa-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "patientRegisterAPI",
            "endpoint": "https://wh126wfix0.execute-api.sa-east-1.amazonaws.com/dev",
            "region": "sa-east-1"
        }
    ]
};


export default awsmobile;
